/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaclientesoap;

import java.awt.Color;
import javax.swing.JOptionPane;
import ws.WSOperaciones;
import ws.WSOperaciones_Service;

/**
 *
 * @author PC
 */
public class RegistroUsuario extends javax.swing.JFrame {

    WSOperaciones_Service servicio = new WSOperaciones_Service();
    WSOperaciones Funciones = servicio.getWSOperacionesPort();
    VistaClienteSoap clase = new VistaClienteSoap();

    public RegistroUsuario() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JButton();
        txtCuenta = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        txtClaveP = new javax.swing.JPasswordField();
        txtClaveS = new javax.swing.JPasswordField();
        BtnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(187, 230, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Registro Usuarios");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 34, 103));
        jLabel13.setText("Saldo inicial");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        BtnRegistrar.setBackground(new java.awt.Color(0, 34, 103));
        BtnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        jPanel4.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));
        jPanel4.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 130, -1));
        jPanel4.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 130, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 34, 103));
        jLabel14.setText("Ingrese Usuario");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 34, 103));
        jLabel15.setText("Ingrese Clave");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 34, 103));
        jLabel16.setText("Repetir Clave");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 34, 103));
        jLabel17.setText("N° Cuenta");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel4.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 130, -1));
        jPanel4.add(txtClaveP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, -1));
        jPanel4.add(txtClaveS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 130, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 270, 370));

        BtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaclientesoap/Img/flecha-izquierda.png"))); // NOI18N
        BtnRegresar.setContentAreaFilled(false);
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaclientesoap/Img/img registrar (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        if (txtClaveP.getText().trim().equals(txtClaveS.getText().trim())) {
           
            Funciones.registrar(this.txtUsuario.getText(), this.txtClaveP.getText(),
                    Double.parseDouble(this.txtSaldo.getText()),this.txtCuenta.getText() );
            clase.Registrar(this.txtUsuario.getText(), this.txtClaveP.getText(), 
                    Double.parseDouble(this.txtSaldo.getText()),this.txtCuenta.getText());
            JOptionPane.showMessageDialog(null, "Usuario registrado");
            limpiarDatos();
            
        } else {
            JOptionPane.showMessageDialog(null, "Las contraseñas son diferentes,Ingrese nuevamente");

        }
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        this.dispose();
        FormAcceso FPrincipal = new FormAcceso();
        FPrincipal.setVisible(true);
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void limpiarDatos() {
        this.txtUsuario.setText("");
        this.txtClaveS.setText("");
        this.txtClaveP.setText("");
        this.txtCuenta.setText("");
        this.txtSaldo.setText("");
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtClaveP;
    private javax.swing.JPasswordField txtClaveS;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtSaldo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
