package vistaclientesoap;

import javax.swing.JOptionPane;
import ws.WSOperaciones;
import ws.WSOperaciones_Service;

public class CuentaUsuario extends javax.swing.JFrame {

    WSOperaciones_Service servicio = null;
    WSOperaciones funciones = null;
    VistaClienteSoap CuentaBanc = new VistaClienteSoap();
    String cuentaP = "";

    public CuentaUsuario(String UsC) {
        initComponents();
        cuentaP = UsC;
        this.setLocationRelativeTo(null);
        servicio = new WSOperaciones_Service();
        funciones = servicio.getWSOperacionesPort();
        CargarDatos(cuentaP);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnIngresar = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        RRetiro = new javax.swing.JRadioButton();
        RDeposito = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        txtUs = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCuenta = new javax.swing.JTextField();
        txtSaldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(187, 230, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cuenta Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        BtnIngresar.setBackground(new java.awt.Color(0, 34, 103));
        BtnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));
        jPanel1.add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 34, 103));
        jLabel6.setText("Valor:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 34, 103));
        jLabel7.setText("Seleccione");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 34, 103));
        jLabel8.setText("opción:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        buttonGroup1.add(RRetiro);
        RRetiro.setForeground(new java.awt.Color(0, 34, 103));
        RRetiro.setText("Retiro");
        jPanel1.add(RRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 70, -1));

        buttonGroup1.add(RDeposito);
        RDeposito.setForeground(new java.awt.Color(0, 34, 103));
        RDeposito.setText("Deposito");
        jPanel1.add(RDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUs.setEditable(false);
        jPanel2.add(txtUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 34, 103));
        jLabel3.setText("Usuario");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtCuenta.setEditable(false);
        jPanel2.add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 130, -1));

        txtSaldo.setEditable(false);
        jPanel2.add(txtSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 34, 103));
        jLabel5.setText("Saldo:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 34, 103));
        jLabel10.setText("N° Cuenta");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 250, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 290, 370));

        BtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaclientesoap/Img/cerrarSesion.png"))); // NOI18N
        BtnSalir.setContentAreaFilled(false);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistaclientesoap/Img/cuenta.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
   if (RDeposito.isSelected()) {
            CuentaBanc.Depositar(cuentaP, Double.parseDouble(this.txtValor.getText()));
            CargarDatos(cuentaP);
            JOptionPane.showMessageDialog(null, "Deposito realizado con exito");
            this.txtValor.setText("");
        } else if (RRetiro.isSelected()) {

            if (Double.parseDouble(txtSaldo.getText()) >= Double.parseDouble(txtValor.getText())) {
                CuentaBanc.Retirar(cuentaP, Double.parseDouble(this.txtValor.getText()));
                CargarDatos(cuentaP);
                 JOptionPane.showMessageDialog(null, "Retiro realizado con exito");
                this.txtValor.setText("");;
            } else {
                 JOptionPane.showMessageDialog(null, "Saldo insuficiente");

            }

        }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
       this.dispose();
        FormAcceso FPrincipal = new FormAcceso();
        FPrincipal.setVisible(true);
    }//GEN-LAST:event_BtnSalirActionPerformed
        void CargarDatos(String NumCuenta) {
        for (int i = 1; i <= CuentaBanc.us - 1; i++) {
            if (NumCuenta.equals(CuentaBanc.user[i].Usuario)) {
                this.txtUs.setText(CuentaBanc.user[i].Usuario);
                this.txtCuenta.setText(CuentaBanc.user[i].NCuenta);
                this.txtSaldo.setText(String.valueOf(CuentaBanc.user[i].Saldo));
                break;
            }
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JRadioButton RDeposito;
    private javax.swing.JRadioButton RRetiro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField txtCuenta;
    public javax.swing.JTextField txtSaldo;
    public javax.swing.JTextField txtUs;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
